name: generate
kind: pipeline
type: docker

steps:
- name: statiq
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
    - dotnet tool restore
    - dotnet restore
    - dotnet cake --target=Run

- name: publish
  image: plugins/s3
  settings:
    bucket: blog-unexpectedeof
    source: ./output
    target: /
    path_style: true
    endpoint: https://minio.unexpectedeof.xyz
    access_key:
      from_secret: minio_access_key_id
    secret_key:
      from_secret: minio_secret_access_key
