theme = "DeepThought"
base_url = "https://burningdaylight.io"
title = "burningdaylight"
default_language = "en"

compile_sass = true
build_search_index = true

highlight_code = true
highlight_theme = "one-dark"

generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "tags", fees = true, paginate_by = 10 },
]

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
navbar_items = [
	{ url = "$BASE_URL/", name = "Home" },
	{ url = "$BASE_URL/posts", name = "Posts" },
	{ url = "$BASE_URL/docs", name = "Docs" },
	{ url = "https://git.burningdaylight.io", name = "Repos" },
	{ url = "https://youtrack.burningdaylight.io/projects", name = "Projects" },
	{ url = "https://teamcity.burningdaylight.io/overview.html?guest=1", name = "Builds" },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-icon.png"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = ""
avatar = "/images/CelestialRings_140x100_07_Animated_ShipsRacing_x1_Optimised.gif"

[extra.social]
github = "n0mn0m"
hackaday = "n0mn0m"
exercism = "n0mn0m"
stackoverflow = "1480185"
pgp = "56B9DC29C24B785FBA66C99EEB589747BCEE2FD1"
h3 = "https://h3lou.org/"
linkedin = "alexhagerman"
